/* !file overlay29 */
/* ApplyMoveEffect = ?????; unknown */
ApplyMoveEffectHookAddr = 0x023302E4;
ApplyMoveEffectJumpAddr = 0x0233310C;
ApplyItemEffectHookAddr = 0x0231C434;
ApplyItemEffectJumpAddr = 0x0231D574;

/* Add your own symbols here... */
SpeedBoostHookAddr = 0x02310EE8;
SpeedBoostJumpAddr = 0x02310F20;

IsTargetInRangeHookAddr = 0x0231B148;
CheckMonsterInPath = 0x0231B1D8;
IsTargetInRangeJumpAddr = 0x0231B1E4;

/* !file arm9 */
ChangeGlobalBorderColor = 0x02027D74;
