/* !file overlay29 */
ApplyMoveEffect = 0x0232E864;
ApplyMoveEffectHookAddr = 0x0232F8A4;
ApplyMoveEffectJumpAddr = 0x023326CC;
ApplyItemEffectHookAddr = 0x0231B9D8;
ApplyItemEffectJumpAddr = 0x0231CB14;

/* Add your own symbols here... */
SpeedBoostHookAddr = 0x02310488;
SpeedBoostJumpAddr = 0x023104C0;

IsTargetInRangeHookAddr = 0x0231A6E8;
CheckMonsterInPath = 0x0231A778;
IsTargetInRangeJumpAddr = 0x0231A794;

/* !file arm9 */
ChangeGlobalBorderColor = 0x02027A80;
